// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booth.proto

#ifndef PROTOBUF_booth_2eproto__INCLUDED
#define PROTOBUF_booth_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace clientmsg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_booth_2eproto();
void protobuf_AssignDesc_booth_2eproto();
void protobuf_ShutdownFile_booth_2eproto();

class HoldBooth;
class BoothState;
class LeaveBooth;
class GetBoothState;

// ===================================================================

class HoldBooth : public ::google::protobuf::Message {
 public:
  HoldBooth();
  virtual ~HoldBooth();

  HoldBooth(const HoldBooth& from);

  inline HoldBooth& operator=(const HoldBooth& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HoldBooth& default_instance();

  void Swap(HoldBooth* other);

  // implements Message ----------------------------------------------

  inline HoldBooth* New() const { return New(NULL); }

  HoldBooth* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HoldBooth& from);
  void MergeFrom(const HoldBooth& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HoldBooth* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 cityid = 1;
  bool has_cityid() const;
  void clear_cityid();
  static const int kCityidFieldNumber = 1;
  ::google::protobuf::uint32 cityid() const;
  void set_cityid(::google::protobuf::uint32 value);

  // optional uint32 boothid = 2;
  bool has_boothid() const;
  void clear_boothid();
  static const int kBoothidFieldNumber = 2;
  ::google::protobuf::uint32 boothid() const;
  void set_boothid(::google::protobuf::uint32 value);

  // optional uint32 charid = 3;
  bool has_charid() const;
  void clear_charid();
  static const int kCharidFieldNumber = 3;
  ::google::protobuf::uint32 charid() const;
  void set_charid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:clientmsg.HoldBooth)
 private:
  inline void set_has_cityid();
  inline void clear_has_cityid();
  inline void set_has_boothid();
  inline void clear_has_boothid();
  inline void set_has_charid();
  inline void clear_has_charid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 cityid_;
  ::google::protobuf::uint32 boothid_;
  ::google::protobuf::uint32 charid_;
  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static HoldBooth* default_instance_;
};
// -------------------------------------------------------------------

class BoothState : public ::google::protobuf::Message {
 public:
  BoothState();
  virtual ~BoothState();

  BoothState(const BoothState& from);

  inline BoothState& operator=(const BoothState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BoothState& default_instance();

  void Swap(BoothState* other);

  // implements Message ----------------------------------------------

  inline BoothState* New() const { return New(NULL); }

  BoothState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BoothState& from);
  void MergeFrom(const BoothState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BoothState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .clientmsg.HoldBooth states = 1;
  int states_size() const;
  void clear_states();
  static const int kStatesFieldNumber = 1;
  const ::clientmsg::HoldBooth& states(int index) const;
  ::clientmsg::HoldBooth* mutable_states(int index);
  ::clientmsg::HoldBooth* add_states();
  const ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >&
      states() const;
  ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >*
      mutable_states();

  // @@protoc_insertion_point(class_scope:clientmsg.BoothState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth > states_;
  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static BoothState* default_instance_;
};
// -------------------------------------------------------------------

class LeaveBooth : public ::google::protobuf::Message {
 public:
  LeaveBooth();
  virtual ~LeaveBooth();

  LeaveBooth(const LeaveBooth& from);

  inline LeaveBooth& operator=(const LeaveBooth& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LeaveBooth& default_instance();

  void Swap(LeaveBooth* other);

  // implements Message ----------------------------------------------

  inline LeaveBooth* New() const { return New(NULL); }

  LeaveBooth* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LeaveBooth& from);
  void MergeFrom(const LeaveBooth& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LeaveBooth* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 boothids = 1;
  int boothids_size() const;
  void clear_boothids();
  static const int kBoothidsFieldNumber = 1;
  ::google::protobuf::uint32 boothids(int index) const;
  void set_boothids(int index, ::google::protobuf::uint32 value);
  void add_boothids(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      boothids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_boothids();

  // @@protoc_insertion_point(class_scope:clientmsg.LeaveBooth)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > boothids_;
  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static LeaveBooth* default_instance_;
};
// -------------------------------------------------------------------

class GetBoothState : public ::google::protobuf::Message {
 public:
  GetBoothState();
  virtual ~GetBoothState();

  GetBoothState(const GetBoothState& from);

  inline GetBoothState& operator=(const GetBoothState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetBoothState& default_instance();

  void Swap(GetBoothState* other);

  // implements Message ----------------------------------------------

  inline GetBoothState* New() const { return New(NULL); }

  GetBoothState* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetBoothState& from);
  void MergeFrom(const GetBoothState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetBoothState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:clientmsg.GetBoothState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static GetBoothState* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HoldBooth

// optional uint32 cityid = 1;
inline bool HoldBooth::has_cityid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HoldBooth::set_has_cityid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HoldBooth::clear_has_cityid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HoldBooth::clear_cityid() {
  cityid_ = 0u;
  clear_has_cityid();
}
inline ::google::protobuf::uint32 HoldBooth::cityid() const {
  // @@protoc_insertion_point(field_get:clientmsg.HoldBooth.cityid)
  return cityid_;
}
inline void HoldBooth::set_cityid(::google::protobuf::uint32 value) {
  set_has_cityid();
  cityid_ = value;
  // @@protoc_insertion_point(field_set:clientmsg.HoldBooth.cityid)
}

// optional uint32 boothid = 2;
inline bool HoldBooth::has_boothid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HoldBooth::set_has_boothid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HoldBooth::clear_has_boothid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HoldBooth::clear_boothid() {
  boothid_ = 0u;
  clear_has_boothid();
}
inline ::google::protobuf::uint32 HoldBooth::boothid() const {
  // @@protoc_insertion_point(field_get:clientmsg.HoldBooth.boothid)
  return boothid_;
}
inline void HoldBooth::set_boothid(::google::protobuf::uint32 value) {
  set_has_boothid();
  boothid_ = value;
  // @@protoc_insertion_point(field_set:clientmsg.HoldBooth.boothid)
}

// optional uint32 charid = 3;
inline bool HoldBooth::has_charid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HoldBooth::set_has_charid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HoldBooth::clear_has_charid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HoldBooth::clear_charid() {
  charid_ = 0u;
  clear_has_charid();
}
inline ::google::protobuf::uint32 HoldBooth::charid() const {
  // @@protoc_insertion_point(field_get:clientmsg.HoldBooth.charid)
  return charid_;
}
inline void HoldBooth::set_charid(::google::protobuf::uint32 value) {
  set_has_charid();
  charid_ = value;
  // @@protoc_insertion_point(field_set:clientmsg.HoldBooth.charid)
}

// -------------------------------------------------------------------

// BoothState

// repeated .clientmsg.HoldBooth states = 1;
inline int BoothState::states_size() const {
  return states_.size();
}
inline void BoothState::clear_states() {
  states_.Clear();
}
inline const ::clientmsg::HoldBooth& BoothState::states(int index) const {
  // @@protoc_insertion_point(field_get:clientmsg.BoothState.states)
  return states_.Get(index);
}
inline ::clientmsg::HoldBooth* BoothState::mutable_states(int index) {
  // @@protoc_insertion_point(field_mutable:clientmsg.BoothState.states)
  return states_.Mutable(index);
}
inline ::clientmsg::HoldBooth* BoothState::add_states() {
  // @@protoc_insertion_point(field_add:clientmsg.BoothState.states)
  return states_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >&
BoothState::states() const {
  // @@protoc_insertion_point(field_list:clientmsg.BoothState.states)
  return states_;
}
inline ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >*
BoothState::mutable_states() {
  // @@protoc_insertion_point(field_mutable_list:clientmsg.BoothState.states)
  return &states_;
}

// -------------------------------------------------------------------

// LeaveBooth

// repeated uint32 boothids = 1;
inline int LeaveBooth::boothids_size() const {
  return boothids_.size();
}
inline void LeaveBooth::clear_boothids() {
  boothids_.Clear();
}
inline ::google::protobuf::uint32 LeaveBooth::boothids(int index) const {
  // @@protoc_insertion_point(field_get:clientmsg.LeaveBooth.boothids)
  return boothids_.Get(index);
}
inline void LeaveBooth::set_boothids(int index, ::google::protobuf::uint32 value) {
  boothids_.Set(index, value);
  // @@protoc_insertion_point(field_set:clientmsg.LeaveBooth.boothids)
}
inline void LeaveBooth::add_boothids(::google::protobuf::uint32 value) {
  boothids_.Add(value);
  // @@protoc_insertion_point(field_add:clientmsg.LeaveBooth.boothids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
LeaveBooth::boothids() const {
  // @@protoc_insertion_point(field_list:clientmsg.LeaveBooth.boothids)
  return boothids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
LeaveBooth::mutable_boothids() {
  // @@protoc_insertion_point(field_mutable_list:clientmsg.LeaveBooth.boothids)
  return &boothids_;
}

// -------------------------------------------------------------------

// GetBoothState

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace clientmsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_booth_2eproto__INCLUDED
