// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dream_hero.proto

#ifndef PROTOBUF_dream_5fhero_2eproto__INCLUDED
#define PROTOBUF_dream_5fhero_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dream_5fhero_2eproto();
void protobuf_AssignDesc_dream_5fhero_2eproto();
void protobuf_ShutdownFile_dream_5fhero_2eproto();

class S2CMsgHeroInit;
class S2CMsgHeroEquip;
class S2CMsgToyInit;
class S2CMsgEquipInit;
class C2SModifySuitNameReq;
class S2CModifySuitNameACK;
class S2CModifySuitErrorACK;
class C2SModifySuitReq;
class S2CModifySuitACK;
class C2SDelSuitReq;
class S2CDelSuitACK;
class C2SVerifyToyCDKeyReq;
class S2CVerifyToyCDKeyErrorACK;
class S2CVerifyToyCDKeyACK;
class S2CEquipLevelUpReq;
class S2CEquipLevelUpACK;
class S2CEquipLevelUpErrorACK;

// ===================================================================

class S2CMsgHeroInit : public ::google::protobuf::Message {
 public:
  S2CMsgHeroInit();
  virtual ~S2CMsgHeroInit();

  S2CMsgHeroInit(const S2CMsgHeroInit& from);

  inline S2CMsgHeroInit& operator=(const S2CMsgHeroInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgHeroInit& default_instance();

  void Swap(S2CMsgHeroInit* other);

  // implements Message ----------------------------------------------

  inline S2CMsgHeroInit* New() const { return New(NULL); }

  S2CMsgHeroInit* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgHeroInit& from);
  void MergeFrom(const S2CMsgHeroInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgHeroInit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.MsgHeroData hero = 1;
  bool has_hero() const;
  void clear_hero();
  static const int kHeroFieldNumber = 1;
  const ::message::MsgHeroData& hero() const;
  ::message::MsgHeroData* mutable_hero();
  ::message::MsgHeroData* release_hero();
  void set_allocated_hero(::message::MsgHeroData* hero);

  // @@protoc_insertion_point(class_scope:message.S2CMsgHeroInit)
 private:
  inline void set_has_hero();
  inline void clear_has_hero();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::MsgHeroData* hero_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgHeroInit* default_instance_;
};
// -------------------------------------------------------------------

class S2CMsgHeroEquip : public ::google::protobuf::Message {
 public:
  S2CMsgHeroEquip();
  virtual ~S2CMsgHeroEquip();

  S2CMsgHeroEquip(const S2CMsgHeroEquip& from);

  inline S2CMsgHeroEquip& operator=(const S2CMsgHeroEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgHeroEquip& default_instance();

  void Swap(S2CMsgHeroEquip* other);

  // implements Message ----------------------------------------------

  inline S2CMsgHeroEquip* New() const { return New(NULL); }

  S2CMsgHeroEquip* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgHeroEquip& from);
  void MergeFrom(const S2CMsgHeroEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgHeroEquip* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .message.MsgEquipData equips = 1;
  int equips_size() const;
  void clear_equips();
  static const int kEquipsFieldNumber = 1;
  const ::message::MsgEquipData& equips(int index) const;
  ::message::MsgEquipData* mutable_equips(int index);
  ::message::MsgEquipData* add_equips();
  const ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >&
      equips() const;
  ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >*
      mutable_equips();

  // required bool end = 2;
  bool has_end() const;
  void clear_end();
  static const int kEndFieldNumber = 2;
  bool end() const;
  void set_end(bool value);

  // required bool begin = 3;
  bool has_begin() const;
  void clear_begin();
  static const int kBeginFieldNumber = 3;
  bool begin() const;
  void set_begin(bool value);

  // @@protoc_insertion_point(class_scope:message.S2CMsgHeroEquip)
 private:
  inline void set_has_end();
  inline void clear_has_end();
  inline void set_has_begin();
  inline void clear_has_begin();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData > equips_;
  bool end_;
  bool begin_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgHeroEquip* default_instance_;
};
// -------------------------------------------------------------------

class S2CMsgToyInit : public ::google::protobuf::Message {
 public:
  S2CMsgToyInit();
  virtual ~S2CMsgToyInit();

  S2CMsgToyInit(const S2CMsgToyInit& from);

  inline S2CMsgToyInit& operator=(const S2CMsgToyInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgToyInit& default_instance();

  void Swap(S2CMsgToyInit* other);

  // implements Message ----------------------------------------------

  inline S2CMsgToyInit* New() const { return New(NULL); }

  S2CMsgToyInit* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgToyInit& from);
  void MergeFrom(const S2CMsgToyInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgToyInit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .message.MsgToyBaseData toys = 1;
  int toys_size() const;
  void clear_toys();
  static const int kToysFieldNumber = 1;
  const ::message::MsgToyBaseData& toys(int index) const;
  ::message::MsgToyBaseData* mutable_toys(int index);
  ::message::MsgToyBaseData* add_toys();
  const ::google::protobuf::RepeatedPtrField< ::message::MsgToyBaseData >&
      toys() const;
  ::google::protobuf::RepeatedPtrField< ::message::MsgToyBaseData >*
      mutable_toys();

  // @@protoc_insertion_point(class_scope:message.S2CMsgToyInit)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::message::MsgToyBaseData > toys_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgToyInit* default_instance_;
};
// -------------------------------------------------------------------

class S2CMsgEquipInit : public ::google::protobuf::Message {
 public:
  S2CMsgEquipInit();
  virtual ~S2CMsgEquipInit();

  S2CMsgEquipInit(const S2CMsgEquipInit& from);

  inline S2CMsgEquipInit& operator=(const S2CMsgEquipInit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CMsgEquipInit& default_instance();

  void Swap(S2CMsgEquipInit* other);

  // implements Message ----------------------------------------------

  inline S2CMsgEquipInit* New() const { return New(NULL); }

  S2CMsgEquipInit* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CMsgEquipInit& from);
  void MergeFrom(const S2CMsgEquipInit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CMsgEquipInit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.S2CMsgHeroEquip equip = 1;
  bool has_equip() const;
  void clear_equip();
  static const int kEquipFieldNumber = 1;
  const ::message::S2CMsgHeroEquip& equip() const;
  ::message::S2CMsgHeroEquip* mutable_equip();
  ::message::S2CMsgHeroEquip* release_equip();
  void set_allocated_equip(::message::S2CMsgHeroEquip* equip);

  // @@protoc_insertion_point(class_scope:message.S2CMsgEquipInit)
 private:
  inline void set_has_equip();
  inline void clear_has_equip();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::S2CMsgHeroEquip* equip_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CMsgEquipInit* default_instance_;
};
// -------------------------------------------------------------------

class C2SModifySuitNameReq : public ::google::protobuf::Message {
 public:
  C2SModifySuitNameReq();
  virtual ~C2SModifySuitNameReq();

  C2SModifySuitNameReq(const C2SModifySuitNameReq& from);

  inline C2SModifySuitNameReq& operator=(const C2SModifySuitNameReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SModifySuitNameReq& default_instance();

  void Swap(C2SModifySuitNameReq* other);

  // implements Message ----------------------------------------------

  inline C2SModifySuitNameReq* New() const { return New(NULL); }

  C2SModifySuitNameReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SModifySuitNameReq& from);
  void MergeFrom(const C2SModifySuitNameReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(C2SModifySuitNameReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 suit_id = 1;
  bool has_suit_id() const;
  void clear_suit_id();
  static const int kSuitIdFieldNumber = 1;
  ::google::protobuf::int32 suit_id() const;
  void set_suit_id(::google::protobuf::int32 value);

  // required string suit_name = 2;
  bool has_suit_name() const;
  void clear_suit_name();
  static const int kSuitNameFieldNumber = 2;
  const ::std::string& suit_name() const;
  void set_suit_name(const ::std::string& value);
  void set_suit_name(const char* value);
  void set_suit_name(const char* value, size_t size);
  ::std::string* mutable_suit_name();
  ::std::string* release_suit_name();
  void set_allocated_suit_name(::std::string* suit_name);

  // @@protoc_insertion_point(class_scope:message.C2SModifySuitNameReq)
 private:
  inline void set_has_suit_id();
  inline void clear_has_suit_id();
  inline void set_has_suit_name();
  inline void clear_has_suit_name();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr suit_name_;
  ::google::protobuf::int32 suit_id_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static C2SModifySuitNameReq* default_instance_;
};
// -------------------------------------------------------------------

class S2CModifySuitNameACK : public ::google::protobuf::Message {
 public:
  S2CModifySuitNameACK();
  virtual ~S2CModifySuitNameACK();

  S2CModifySuitNameACK(const S2CModifySuitNameACK& from);

  inline S2CModifySuitNameACK& operator=(const S2CModifySuitNameACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CModifySuitNameACK& default_instance();

  void Swap(S2CModifySuitNameACK* other);

  // implements Message ----------------------------------------------

  inline S2CModifySuitNameACK* New() const { return New(NULL); }

  S2CModifySuitNameACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CModifySuitNameACK& from);
  void MergeFrom(const S2CModifySuitNameACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CModifySuitNameACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 suit_id = 1;
  bool has_suit_id() const;
  void clear_suit_id();
  static const int kSuitIdFieldNumber = 1;
  ::google::protobuf::int32 suit_id() const;
  void set_suit_id(::google::protobuf::int32 value);

  // required string suit_name = 2;
  bool has_suit_name() const;
  void clear_suit_name();
  static const int kSuitNameFieldNumber = 2;
  const ::std::string& suit_name() const;
  void set_suit_name(const ::std::string& value);
  void set_suit_name(const char* value);
  void set_suit_name(const char* value, size_t size);
  ::std::string* mutable_suit_name();
  ::std::string* release_suit_name();
  void set_allocated_suit_name(::std::string* suit_name);

  // @@protoc_insertion_point(class_scope:message.S2CModifySuitNameACK)
 private:
  inline void set_has_suit_id();
  inline void clear_has_suit_id();
  inline void set_has_suit_name();
  inline void clear_has_suit_name();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr suit_name_;
  ::google::protobuf::int32 suit_id_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CModifySuitNameACK* default_instance_;
};
// -------------------------------------------------------------------

class S2CModifySuitErrorACK : public ::google::protobuf::Message {
 public:
  S2CModifySuitErrorACK();
  virtual ~S2CModifySuitErrorACK();

  S2CModifySuitErrorACK(const S2CModifySuitErrorACK& from);

  inline S2CModifySuitErrorACK& operator=(const S2CModifySuitErrorACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CModifySuitErrorACK& default_instance();

  void Swap(S2CModifySuitErrorACK* other);

  // implements Message ----------------------------------------------

  inline S2CModifySuitErrorACK* New() const { return New(NULL); }

  S2CModifySuitErrorACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CModifySuitErrorACK& from);
  void MergeFrom(const S2CModifySuitErrorACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CModifySuitErrorACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 suit_id = 1;
  bool has_suit_id() const;
  void clear_suit_id();
  static const int kSuitIdFieldNumber = 1;
  ::google::protobuf::int32 suit_id() const;
  void set_suit_id(::google::protobuf::int32 value);

  // required .message.HeroErrorCode error = 2 [default = no_error];
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  ::message::HeroErrorCode error() const;
  void set_error(::message::HeroErrorCode value);

  // @@protoc_insertion_point(class_scope:message.S2CModifySuitErrorACK)
 private:
  inline void set_has_suit_id();
  inline void clear_has_suit_id();
  inline void set_has_error();
  inline void clear_has_error();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 suit_id_;
  int error_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CModifySuitErrorACK* default_instance_;
};
// -------------------------------------------------------------------

class C2SModifySuitReq : public ::google::protobuf::Message {
 public:
  C2SModifySuitReq();
  virtual ~C2SModifySuitReq();

  C2SModifySuitReq(const C2SModifySuitReq& from);

  inline C2SModifySuitReq& operator=(const C2SModifySuitReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SModifySuitReq& default_instance();

  void Swap(C2SModifySuitReq* other);

  // implements Message ----------------------------------------------

  inline C2SModifySuitReq* New() const { return New(NULL); }

  C2SModifySuitReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SModifySuitReq& from);
  void MergeFrom(const C2SModifySuitReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(C2SModifySuitReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.MsgSuitData data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::message::MsgSuitData& data() const;
  ::message::MsgSuitData* mutable_data();
  ::message::MsgSuitData* release_data();
  void set_allocated_data(::message::MsgSuitData* data);

  // @@protoc_insertion_point(class_scope:message.C2SModifySuitReq)
 private:
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::MsgSuitData* data_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static C2SModifySuitReq* default_instance_;
};
// -------------------------------------------------------------------

class S2CModifySuitACK : public ::google::protobuf::Message {
 public:
  S2CModifySuitACK();
  virtual ~S2CModifySuitACK();

  S2CModifySuitACK(const S2CModifySuitACK& from);

  inline S2CModifySuitACK& operator=(const S2CModifySuitACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CModifySuitACK& default_instance();

  void Swap(S2CModifySuitACK* other);

  // implements Message ----------------------------------------------

  inline S2CModifySuitACK* New() const { return New(NULL); }

  S2CModifySuitACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CModifySuitACK& from);
  void MergeFrom(const S2CModifySuitACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CModifySuitACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 suit_id = 1;
  bool has_suit_id() const;
  void clear_suit_id();
  static const int kSuitIdFieldNumber = 1;
  ::google::protobuf::int32 suit_id() const;
  void set_suit_id(::google::protobuf::int32 value);

  // required .message.HeroErrorCode error = 2 [default = no_error];
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  ::message::HeroErrorCode error() const;
  void set_error(::message::HeroErrorCode value);

  // @@protoc_insertion_point(class_scope:message.S2CModifySuitACK)
 private:
  inline void set_has_suit_id();
  inline void clear_has_suit_id();
  inline void set_has_error();
  inline void clear_has_error();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 suit_id_;
  int error_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CModifySuitACK* default_instance_;
};
// -------------------------------------------------------------------

class C2SDelSuitReq : public ::google::protobuf::Message {
 public:
  C2SDelSuitReq();
  virtual ~C2SDelSuitReq();

  C2SDelSuitReq(const C2SDelSuitReq& from);

  inline C2SDelSuitReq& operator=(const C2SDelSuitReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SDelSuitReq& default_instance();

  void Swap(C2SDelSuitReq* other);

  // implements Message ----------------------------------------------

  inline C2SDelSuitReq* New() const { return New(NULL); }

  C2SDelSuitReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SDelSuitReq& from);
  void MergeFrom(const C2SDelSuitReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(C2SDelSuitReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 suit_id = 1;
  bool has_suit_id() const;
  void clear_suit_id();
  static const int kSuitIdFieldNumber = 1;
  ::google::protobuf::int32 suit_id() const;
  void set_suit_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.C2SDelSuitReq)
 private:
  inline void set_has_suit_id();
  inline void clear_has_suit_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 suit_id_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static C2SDelSuitReq* default_instance_;
};
// -------------------------------------------------------------------

class S2CDelSuitACK : public ::google::protobuf::Message {
 public:
  S2CDelSuitACK();
  virtual ~S2CDelSuitACK();

  S2CDelSuitACK(const S2CDelSuitACK& from);

  inline S2CDelSuitACK& operator=(const S2CDelSuitACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CDelSuitACK& default_instance();

  void Swap(S2CDelSuitACK* other);

  // implements Message ----------------------------------------------

  inline S2CDelSuitACK* New() const { return New(NULL); }

  S2CDelSuitACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CDelSuitACK& from);
  void MergeFrom(const S2CDelSuitACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CDelSuitACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 suit_id = 1;
  bool has_suit_id() const;
  void clear_suit_id();
  static const int kSuitIdFieldNumber = 1;
  ::google::protobuf::int32 suit_id() const;
  void set_suit_id(::google::protobuf::int32 value);

  // required .message.HeroErrorCode error = 2 [default = no_error];
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  ::message::HeroErrorCode error() const;
  void set_error(::message::HeroErrorCode value);

  // @@protoc_insertion_point(class_scope:message.S2CDelSuitACK)
 private:
  inline void set_has_suit_id();
  inline void clear_has_suit_id();
  inline void set_has_error();
  inline void clear_has_error();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 suit_id_;
  int error_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CDelSuitACK* default_instance_;
};
// -------------------------------------------------------------------

class C2SVerifyToyCDKeyReq : public ::google::protobuf::Message {
 public:
  C2SVerifyToyCDKeyReq();
  virtual ~C2SVerifyToyCDKeyReq();

  C2SVerifyToyCDKeyReq(const C2SVerifyToyCDKeyReq& from);

  inline C2SVerifyToyCDKeyReq& operator=(const C2SVerifyToyCDKeyReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SVerifyToyCDKeyReq& default_instance();

  void Swap(C2SVerifyToyCDKeyReq* other);

  // implements Message ----------------------------------------------

  inline C2SVerifyToyCDKeyReq* New() const { return New(NULL); }

  C2SVerifyToyCDKeyReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SVerifyToyCDKeyReq& from);
  void MergeFrom(const C2SVerifyToyCDKeyReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(C2SVerifyToyCDKeyReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cd_key = 1;
  bool has_cd_key() const;
  void clear_cd_key();
  static const int kCdKeyFieldNumber = 1;
  const ::std::string& cd_key() const;
  void set_cd_key(const ::std::string& value);
  void set_cd_key(const char* value);
  void set_cd_key(const char* value, size_t size);
  ::std::string* mutable_cd_key();
  ::std::string* release_cd_key();
  void set_allocated_cd_key(::std::string* cd_key);

  // @@protoc_insertion_point(class_scope:message.C2SVerifyToyCDKeyReq)
 private:
  inline void set_has_cd_key();
  inline void clear_has_cd_key();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr cd_key_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static C2SVerifyToyCDKeyReq* default_instance_;
};
// -------------------------------------------------------------------

class S2CVerifyToyCDKeyErrorACK : public ::google::protobuf::Message {
 public:
  S2CVerifyToyCDKeyErrorACK();
  virtual ~S2CVerifyToyCDKeyErrorACK();

  S2CVerifyToyCDKeyErrorACK(const S2CVerifyToyCDKeyErrorACK& from);

  inline S2CVerifyToyCDKeyErrorACK& operator=(const S2CVerifyToyCDKeyErrorACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CVerifyToyCDKeyErrorACK& default_instance();

  void Swap(S2CVerifyToyCDKeyErrorACK* other);

  // implements Message ----------------------------------------------

  inline S2CVerifyToyCDKeyErrorACK* New() const { return New(NULL); }

  S2CVerifyToyCDKeyErrorACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CVerifyToyCDKeyErrorACK& from);
  void MergeFrom(const S2CVerifyToyCDKeyErrorACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CVerifyToyCDKeyErrorACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cd_key = 1;
  bool has_cd_key() const;
  void clear_cd_key();
  static const int kCdKeyFieldNumber = 1;
  const ::std::string& cd_key() const;
  void set_cd_key(const ::std::string& value);
  void set_cd_key(const char* value);
  void set_cd_key(const char* value, size_t size);
  ::std::string* mutable_cd_key();
  ::std::string* release_cd_key();
  void set_allocated_cd_key(::std::string* cd_key);

  // required .message.HeroErrorCode error = 2 [default = no_error];
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  ::message::HeroErrorCode error() const;
  void set_error(::message::HeroErrorCode value);

  // @@protoc_insertion_point(class_scope:message.S2CVerifyToyCDKeyErrorACK)
 private:
  inline void set_has_cd_key();
  inline void clear_has_cd_key();
  inline void set_has_error();
  inline void clear_has_error();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr cd_key_;
  int error_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CVerifyToyCDKeyErrorACK* default_instance_;
};
// -------------------------------------------------------------------

class S2CVerifyToyCDKeyACK : public ::google::protobuf::Message {
 public:
  S2CVerifyToyCDKeyACK();
  virtual ~S2CVerifyToyCDKeyACK();

  S2CVerifyToyCDKeyACK(const S2CVerifyToyCDKeyACK& from);

  inline S2CVerifyToyCDKeyACK& operator=(const S2CVerifyToyCDKeyACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CVerifyToyCDKeyACK& default_instance();

  void Swap(S2CVerifyToyCDKeyACK* other);

  // implements Message ----------------------------------------------

  inline S2CVerifyToyCDKeyACK* New() const { return New(NULL); }

  S2CVerifyToyCDKeyACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CVerifyToyCDKeyACK& from);
  void MergeFrom(const S2CVerifyToyCDKeyACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CVerifyToyCDKeyACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .message.MsgToyData ToyData = 1;
  bool has_toydata() const;
  void clear_toydata();
  static const int kToyDataFieldNumber = 1;
  const ::message::MsgToyData& toydata() const;
  ::message::MsgToyData* mutable_toydata();
  ::message::MsgToyData* release_toydata();
  void set_allocated_toydata(::message::MsgToyData* toydata);

  // @@protoc_insertion_point(class_scope:message.S2CVerifyToyCDKeyACK)
 private:
  inline void set_has_toydata();
  inline void clear_has_toydata();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::message::MsgToyData* toydata_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CVerifyToyCDKeyACK* default_instance_;
};
// -------------------------------------------------------------------

class S2CEquipLevelUpReq : public ::google::protobuf::Message {
 public:
  S2CEquipLevelUpReq();
  virtual ~S2CEquipLevelUpReq();

  S2CEquipLevelUpReq(const S2CEquipLevelUpReq& from);

  inline S2CEquipLevelUpReq& operator=(const S2CEquipLevelUpReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CEquipLevelUpReq& default_instance();

  void Swap(S2CEquipLevelUpReq* other);

  // implements Message ----------------------------------------------

  inline S2CEquipLevelUpReq* New() const { return New(NULL); }

  S2CEquipLevelUpReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CEquipLevelUpReq& from);
  void MergeFrom(const S2CEquipLevelUpReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CEquipLevelUpReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 equip_id = 1;
  bool has_equip_id() const;
  void clear_equip_id();
  static const int kEquipIdFieldNumber = 1;
  ::google::protobuf::uint64 equip_id() const;
  void set_equip_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:message.S2CEquipLevelUpReq)
 private:
  inline void set_has_equip_id();
  inline void clear_has_equip_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 equip_id_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CEquipLevelUpReq* default_instance_;
};
// -------------------------------------------------------------------

class S2CEquipLevelUpACK : public ::google::protobuf::Message {
 public:
  S2CEquipLevelUpACK();
  virtual ~S2CEquipLevelUpACK();

  S2CEquipLevelUpACK(const S2CEquipLevelUpACK& from);

  inline S2CEquipLevelUpACK& operator=(const S2CEquipLevelUpACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CEquipLevelUpACK& default_instance();

  void Swap(S2CEquipLevelUpACK* other);

  // implements Message ----------------------------------------------

  inline S2CEquipLevelUpACK* New() const { return New(NULL); }

  S2CEquipLevelUpACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CEquipLevelUpACK& from);
  void MergeFrom(const S2CEquipLevelUpACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CEquipLevelUpACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 equip_id = 1;
  bool has_equip_id() const;
  void clear_equip_id();
  static const int kEquipIdFieldNumber = 1;
  ::google::protobuf::uint64 equip_id() const;
  void set_equip_id(::google::protobuf::uint64 value);

  // required int32 level = 2;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // required int32 gold = 3;
  bool has_gold() const;
  void clear_gold();
  static const int kGoldFieldNumber = 3;
  ::google::protobuf::int32 gold() const;
  void set_gold(::google::protobuf::int32 value);

  // required int32 count = 4;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 4;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // required int32 diamand = 5;
  bool has_diamand() const;
  void clear_diamand();
  static const int kDiamandFieldNumber = 5;
  ::google::protobuf::int32 diamand() const;
  void set_diamand(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:message.S2CEquipLevelUpACK)
 private:
  inline void set_has_equip_id();
  inline void clear_has_equip_id();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_gold();
  inline void clear_has_gold();
  inline void set_has_count();
  inline void clear_has_count();
  inline void set_has_diamand();
  inline void clear_has_diamand();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 equip_id_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 gold_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 diamand_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CEquipLevelUpACK* default_instance_;
};
// -------------------------------------------------------------------

class S2CEquipLevelUpErrorACK : public ::google::protobuf::Message {
 public:
  S2CEquipLevelUpErrorACK();
  virtual ~S2CEquipLevelUpErrorACK();

  S2CEquipLevelUpErrorACK(const S2CEquipLevelUpErrorACK& from);

  inline S2CEquipLevelUpErrorACK& operator=(const S2CEquipLevelUpErrorACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CEquipLevelUpErrorACK& default_instance();

  void Swap(S2CEquipLevelUpErrorACK* other);

  // implements Message ----------------------------------------------

  inline S2CEquipLevelUpErrorACK* New() const { return New(NULL); }

  S2CEquipLevelUpErrorACK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CEquipLevelUpErrorACK& from);
  void MergeFrom(const S2CEquipLevelUpErrorACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2CEquipLevelUpErrorACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 equip_id = 1;
  bool has_equip_id() const;
  void clear_equip_id();
  static const int kEquipIdFieldNumber = 1;
  ::google::protobuf::uint64 equip_id() const;
  void set_equip_id(::google::protobuf::uint64 value);

  // required .message.HeroErrorCode error = 2 [default = no_error];
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  ::message::HeroErrorCode error() const;
  void set_error(::message::HeroErrorCode value);

  // @@protoc_insertion_point(class_scope:message.S2CEquipLevelUpErrorACK)
 private:
  inline void set_has_equip_id();
  inline void clear_has_equip_id();
  inline void set_has_error();
  inline void clear_has_error();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 equip_id_;
  int error_;
  friend void  protobuf_AddDesc_dream_5fhero_2eproto();
  friend void protobuf_AssignDesc_dream_5fhero_2eproto();
  friend void protobuf_ShutdownFile_dream_5fhero_2eproto();

  void InitAsDefaultInstance();
  static S2CEquipLevelUpErrorACK* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// S2CMsgHeroInit

// required .message.MsgHeroData hero = 1;
inline bool S2CMsgHeroInit::has_hero() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CMsgHeroInit::set_has_hero() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CMsgHeroInit::clear_has_hero() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CMsgHeroInit::clear_hero() {
  if (hero_ != NULL) hero_->::message::MsgHeroData::Clear();
  clear_has_hero();
}
inline const ::message::MsgHeroData& S2CMsgHeroInit::hero() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroInit.hero)
  return hero_ != NULL ? *hero_ : *default_instance_->hero_;
}
inline ::message::MsgHeroData* S2CMsgHeroInit::mutable_hero() {
  set_has_hero();
  if (hero_ == NULL) {
    hero_ = new ::message::MsgHeroData;
  }
  // @@protoc_insertion_point(field_mutable:message.S2CMsgHeroInit.hero)
  return hero_;
}
inline ::message::MsgHeroData* S2CMsgHeroInit::release_hero() {
  clear_has_hero();
  ::message::MsgHeroData* temp = hero_;
  hero_ = NULL;
  return temp;
}
inline void S2CMsgHeroInit::set_allocated_hero(::message::MsgHeroData* hero) {
  delete hero_;
  hero_ = hero;
  if (hero) {
    set_has_hero();
  } else {
    clear_has_hero();
  }
  // @@protoc_insertion_point(field_set_allocated:message.S2CMsgHeroInit.hero)
}

// -------------------------------------------------------------------

// S2CMsgHeroEquip

// repeated .message.MsgEquipData equips = 1;
inline int S2CMsgHeroEquip::equips_size() const {
  return equips_.size();
}
inline void S2CMsgHeroEquip::clear_equips() {
  equips_.Clear();
}
inline const ::message::MsgEquipData& S2CMsgHeroEquip::equips(int index) const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroEquip.equips)
  return equips_.Get(index);
}
inline ::message::MsgEquipData* S2CMsgHeroEquip::mutable_equips(int index) {
  // @@protoc_insertion_point(field_mutable:message.S2CMsgHeroEquip.equips)
  return equips_.Mutable(index);
}
inline ::message::MsgEquipData* S2CMsgHeroEquip::add_equips() {
  // @@protoc_insertion_point(field_add:message.S2CMsgHeroEquip.equips)
  return equips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >&
S2CMsgHeroEquip::equips() const {
  // @@protoc_insertion_point(field_list:message.S2CMsgHeroEquip.equips)
  return equips_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::MsgEquipData >*
S2CMsgHeroEquip::mutable_equips() {
  // @@protoc_insertion_point(field_mutable_list:message.S2CMsgHeroEquip.equips)
  return &equips_;
}

// required bool end = 2;
inline bool S2CMsgHeroEquip::has_end() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CMsgHeroEquip::set_has_end() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CMsgHeroEquip::clear_has_end() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CMsgHeroEquip::clear_end() {
  end_ = false;
  clear_has_end();
}
inline bool S2CMsgHeroEquip::end() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroEquip.end)
  return end_;
}
inline void S2CMsgHeroEquip::set_end(bool value) {
  set_has_end();
  end_ = value;
  // @@protoc_insertion_point(field_set:message.S2CMsgHeroEquip.end)
}

// required bool begin = 3;
inline bool S2CMsgHeroEquip::has_begin() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S2CMsgHeroEquip::set_has_begin() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S2CMsgHeroEquip::clear_has_begin() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S2CMsgHeroEquip::clear_begin() {
  begin_ = false;
  clear_has_begin();
}
inline bool S2CMsgHeroEquip::begin() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgHeroEquip.begin)
  return begin_;
}
inline void S2CMsgHeroEquip::set_begin(bool value) {
  set_has_begin();
  begin_ = value;
  // @@protoc_insertion_point(field_set:message.S2CMsgHeroEquip.begin)
}

// -------------------------------------------------------------------

// S2CMsgToyInit

// repeated .message.MsgToyBaseData toys = 1;
inline int S2CMsgToyInit::toys_size() const {
  return toys_.size();
}
inline void S2CMsgToyInit::clear_toys() {
  toys_.Clear();
}
inline const ::message::MsgToyBaseData& S2CMsgToyInit::toys(int index) const {
  // @@protoc_insertion_point(field_get:message.S2CMsgToyInit.toys)
  return toys_.Get(index);
}
inline ::message::MsgToyBaseData* S2CMsgToyInit::mutable_toys(int index) {
  // @@protoc_insertion_point(field_mutable:message.S2CMsgToyInit.toys)
  return toys_.Mutable(index);
}
inline ::message::MsgToyBaseData* S2CMsgToyInit::add_toys() {
  // @@protoc_insertion_point(field_add:message.S2CMsgToyInit.toys)
  return toys_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::message::MsgToyBaseData >&
S2CMsgToyInit::toys() const {
  // @@protoc_insertion_point(field_list:message.S2CMsgToyInit.toys)
  return toys_;
}
inline ::google::protobuf::RepeatedPtrField< ::message::MsgToyBaseData >*
S2CMsgToyInit::mutable_toys() {
  // @@protoc_insertion_point(field_mutable_list:message.S2CMsgToyInit.toys)
  return &toys_;
}

// -------------------------------------------------------------------

// S2CMsgEquipInit

// required .message.S2CMsgHeroEquip equip = 1;
inline bool S2CMsgEquipInit::has_equip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CMsgEquipInit::set_has_equip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CMsgEquipInit::clear_has_equip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CMsgEquipInit::clear_equip() {
  if (equip_ != NULL) equip_->::message::S2CMsgHeroEquip::Clear();
  clear_has_equip();
}
inline const ::message::S2CMsgHeroEquip& S2CMsgEquipInit::equip() const {
  // @@protoc_insertion_point(field_get:message.S2CMsgEquipInit.equip)
  return equip_ != NULL ? *equip_ : *default_instance_->equip_;
}
inline ::message::S2CMsgHeroEquip* S2CMsgEquipInit::mutable_equip() {
  set_has_equip();
  if (equip_ == NULL) {
    equip_ = new ::message::S2CMsgHeroEquip;
  }
  // @@protoc_insertion_point(field_mutable:message.S2CMsgEquipInit.equip)
  return equip_;
}
inline ::message::S2CMsgHeroEquip* S2CMsgEquipInit::release_equip() {
  clear_has_equip();
  ::message::S2CMsgHeroEquip* temp = equip_;
  equip_ = NULL;
  return temp;
}
inline void S2CMsgEquipInit::set_allocated_equip(::message::S2CMsgHeroEquip* equip) {
  delete equip_;
  equip_ = equip;
  if (equip) {
    set_has_equip();
  } else {
    clear_has_equip();
  }
  // @@protoc_insertion_point(field_set_allocated:message.S2CMsgEquipInit.equip)
}

// -------------------------------------------------------------------

// C2SModifySuitNameReq

// required int32 suit_id = 1;
inline bool C2SModifySuitNameReq::has_suit_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SModifySuitNameReq::set_has_suit_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SModifySuitNameReq::clear_has_suit_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SModifySuitNameReq::clear_suit_id() {
  suit_id_ = 0;
  clear_has_suit_id();
}
inline ::google::protobuf::int32 C2SModifySuitNameReq::suit_id() const {
  // @@protoc_insertion_point(field_get:message.C2SModifySuitNameReq.suit_id)
  return suit_id_;
}
inline void C2SModifySuitNameReq::set_suit_id(::google::protobuf::int32 value) {
  set_has_suit_id();
  suit_id_ = value;
  // @@protoc_insertion_point(field_set:message.C2SModifySuitNameReq.suit_id)
}

// required string suit_name = 2;
inline bool C2SModifySuitNameReq::has_suit_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2SModifySuitNameReq::set_has_suit_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2SModifySuitNameReq::clear_has_suit_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2SModifySuitNameReq::clear_suit_name() {
  suit_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_suit_name();
}
inline const ::std::string& C2SModifySuitNameReq::suit_name() const {
  // @@protoc_insertion_point(field_get:message.C2SModifySuitNameReq.suit_name)
  return suit_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2SModifySuitNameReq::set_suit_name(const ::std::string& value) {
  set_has_suit_name();
  suit_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.C2SModifySuitNameReq.suit_name)
}
inline void C2SModifySuitNameReq::set_suit_name(const char* value) {
  set_has_suit_name();
  suit_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.C2SModifySuitNameReq.suit_name)
}
inline void C2SModifySuitNameReq::set_suit_name(const char* value, size_t size) {
  set_has_suit_name();
  suit_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.C2SModifySuitNameReq.suit_name)
}
inline ::std::string* C2SModifySuitNameReq::mutable_suit_name() {
  set_has_suit_name();
  // @@protoc_insertion_point(field_mutable:message.C2SModifySuitNameReq.suit_name)
  return suit_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2SModifySuitNameReq::release_suit_name() {
  clear_has_suit_name();
  return suit_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2SModifySuitNameReq::set_allocated_suit_name(::std::string* suit_name) {
  if (suit_name != NULL) {
    set_has_suit_name();
  } else {
    clear_has_suit_name();
  }
  suit_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), suit_name);
  // @@protoc_insertion_point(field_set_allocated:message.C2SModifySuitNameReq.suit_name)
}

// -------------------------------------------------------------------

// S2CModifySuitNameACK

// required int32 suit_id = 1;
inline bool S2CModifySuitNameACK::has_suit_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CModifySuitNameACK::set_has_suit_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CModifySuitNameACK::clear_has_suit_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CModifySuitNameACK::clear_suit_id() {
  suit_id_ = 0;
  clear_has_suit_id();
}
inline ::google::protobuf::int32 S2CModifySuitNameACK::suit_id() const {
  // @@protoc_insertion_point(field_get:message.S2CModifySuitNameACK.suit_id)
  return suit_id_;
}
inline void S2CModifySuitNameACK::set_suit_id(::google::protobuf::int32 value) {
  set_has_suit_id();
  suit_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CModifySuitNameACK.suit_id)
}

// required string suit_name = 2;
inline bool S2CModifySuitNameACK::has_suit_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CModifySuitNameACK::set_has_suit_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CModifySuitNameACK::clear_has_suit_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CModifySuitNameACK::clear_suit_name() {
  suit_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_suit_name();
}
inline const ::std::string& S2CModifySuitNameACK::suit_name() const {
  // @@protoc_insertion_point(field_get:message.S2CModifySuitNameACK.suit_name)
  return suit_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void S2CModifySuitNameACK::set_suit_name(const ::std::string& value) {
  set_has_suit_name();
  suit_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.S2CModifySuitNameACK.suit_name)
}
inline void S2CModifySuitNameACK::set_suit_name(const char* value) {
  set_has_suit_name();
  suit_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.S2CModifySuitNameACK.suit_name)
}
inline void S2CModifySuitNameACK::set_suit_name(const char* value, size_t size) {
  set_has_suit_name();
  suit_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.S2CModifySuitNameACK.suit_name)
}
inline ::std::string* S2CModifySuitNameACK::mutable_suit_name() {
  set_has_suit_name();
  // @@protoc_insertion_point(field_mutable:message.S2CModifySuitNameACK.suit_name)
  return suit_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* S2CModifySuitNameACK::release_suit_name() {
  clear_has_suit_name();
  return suit_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void S2CModifySuitNameACK::set_allocated_suit_name(::std::string* suit_name) {
  if (suit_name != NULL) {
    set_has_suit_name();
  } else {
    clear_has_suit_name();
  }
  suit_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), suit_name);
  // @@protoc_insertion_point(field_set_allocated:message.S2CModifySuitNameACK.suit_name)
}

// -------------------------------------------------------------------

// S2CModifySuitErrorACK

// required int32 suit_id = 1;
inline bool S2CModifySuitErrorACK::has_suit_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CModifySuitErrorACK::set_has_suit_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CModifySuitErrorACK::clear_has_suit_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CModifySuitErrorACK::clear_suit_id() {
  suit_id_ = 0;
  clear_has_suit_id();
}
inline ::google::protobuf::int32 S2CModifySuitErrorACK::suit_id() const {
  // @@protoc_insertion_point(field_get:message.S2CModifySuitErrorACK.suit_id)
  return suit_id_;
}
inline void S2CModifySuitErrorACK::set_suit_id(::google::protobuf::int32 value) {
  set_has_suit_id();
  suit_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CModifySuitErrorACK.suit_id)
}

// required .message.HeroErrorCode error = 2 [default = no_error];
inline bool S2CModifySuitErrorACK::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CModifySuitErrorACK::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CModifySuitErrorACK::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CModifySuitErrorACK::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::message::HeroErrorCode S2CModifySuitErrorACK::error() const {
  // @@protoc_insertion_point(field_get:message.S2CModifySuitErrorACK.error)
  return static_cast< ::message::HeroErrorCode >(error_);
}
inline void S2CModifySuitErrorACK::set_error(::message::HeroErrorCode value) {
  assert(::message::HeroErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:message.S2CModifySuitErrorACK.error)
}

// -------------------------------------------------------------------

// C2SModifySuitReq

// required .message.MsgSuitData data = 1;
inline bool C2SModifySuitReq::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SModifySuitReq::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SModifySuitReq::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SModifySuitReq::clear_data() {
  if (data_ != NULL) data_->::message::MsgSuitData::Clear();
  clear_has_data();
}
inline const ::message::MsgSuitData& C2SModifySuitReq::data() const {
  // @@protoc_insertion_point(field_get:message.C2SModifySuitReq.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
inline ::message::MsgSuitData* C2SModifySuitReq::mutable_data() {
  set_has_data();
  if (data_ == NULL) {
    data_ = new ::message::MsgSuitData;
  }
  // @@protoc_insertion_point(field_mutable:message.C2SModifySuitReq.data)
  return data_;
}
inline ::message::MsgSuitData* C2SModifySuitReq::release_data() {
  clear_has_data();
  ::message::MsgSuitData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void C2SModifySuitReq::set_allocated_data(::message::MsgSuitData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
  // @@protoc_insertion_point(field_set_allocated:message.C2SModifySuitReq.data)
}

// -------------------------------------------------------------------

// S2CModifySuitACK

// required int32 suit_id = 1;
inline bool S2CModifySuitACK::has_suit_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CModifySuitACK::set_has_suit_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CModifySuitACK::clear_has_suit_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CModifySuitACK::clear_suit_id() {
  suit_id_ = 0;
  clear_has_suit_id();
}
inline ::google::protobuf::int32 S2CModifySuitACK::suit_id() const {
  // @@protoc_insertion_point(field_get:message.S2CModifySuitACK.suit_id)
  return suit_id_;
}
inline void S2CModifySuitACK::set_suit_id(::google::protobuf::int32 value) {
  set_has_suit_id();
  suit_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CModifySuitACK.suit_id)
}

// required .message.HeroErrorCode error = 2 [default = no_error];
inline bool S2CModifySuitACK::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CModifySuitACK::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CModifySuitACK::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CModifySuitACK::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::message::HeroErrorCode S2CModifySuitACK::error() const {
  // @@protoc_insertion_point(field_get:message.S2CModifySuitACK.error)
  return static_cast< ::message::HeroErrorCode >(error_);
}
inline void S2CModifySuitACK::set_error(::message::HeroErrorCode value) {
  assert(::message::HeroErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:message.S2CModifySuitACK.error)
}

// -------------------------------------------------------------------

// C2SDelSuitReq

// required int32 suit_id = 1;
inline bool C2SDelSuitReq::has_suit_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SDelSuitReq::set_has_suit_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SDelSuitReq::clear_has_suit_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SDelSuitReq::clear_suit_id() {
  suit_id_ = 0;
  clear_has_suit_id();
}
inline ::google::protobuf::int32 C2SDelSuitReq::suit_id() const {
  // @@protoc_insertion_point(field_get:message.C2SDelSuitReq.suit_id)
  return suit_id_;
}
inline void C2SDelSuitReq::set_suit_id(::google::protobuf::int32 value) {
  set_has_suit_id();
  suit_id_ = value;
  // @@protoc_insertion_point(field_set:message.C2SDelSuitReq.suit_id)
}

// -------------------------------------------------------------------

// S2CDelSuitACK

// required int32 suit_id = 1;
inline bool S2CDelSuitACK::has_suit_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CDelSuitACK::set_has_suit_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CDelSuitACK::clear_has_suit_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CDelSuitACK::clear_suit_id() {
  suit_id_ = 0;
  clear_has_suit_id();
}
inline ::google::protobuf::int32 S2CDelSuitACK::suit_id() const {
  // @@protoc_insertion_point(field_get:message.S2CDelSuitACK.suit_id)
  return suit_id_;
}
inline void S2CDelSuitACK::set_suit_id(::google::protobuf::int32 value) {
  set_has_suit_id();
  suit_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CDelSuitACK.suit_id)
}

// required .message.HeroErrorCode error = 2 [default = no_error];
inline bool S2CDelSuitACK::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CDelSuitACK::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CDelSuitACK::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CDelSuitACK::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::message::HeroErrorCode S2CDelSuitACK::error() const {
  // @@protoc_insertion_point(field_get:message.S2CDelSuitACK.error)
  return static_cast< ::message::HeroErrorCode >(error_);
}
inline void S2CDelSuitACK::set_error(::message::HeroErrorCode value) {
  assert(::message::HeroErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:message.S2CDelSuitACK.error)
}

// -------------------------------------------------------------------

// C2SVerifyToyCDKeyReq

// required string cd_key = 1;
inline bool C2SVerifyToyCDKeyReq::has_cd_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SVerifyToyCDKeyReq::set_has_cd_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SVerifyToyCDKeyReq::clear_has_cd_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SVerifyToyCDKeyReq::clear_cd_key() {
  cd_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cd_key();
}
inline const ::std::string& C2SVerifyToyCDKeyReq::cd_key() const {
  // @@protoc_insertion_point(field_get:message.C2SVerifyToyCDKeyReq.cd_key)
  return cd_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2SVerifyToyCDKeyReq::set_cd_key(const ::std::string& value) {
  set_has_cd_key();
  cd_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.C2SVerifyToyCDKeyReq.cd_key)
}
inline void C2SVerifyToyCDKeyReq::set_cd_key(const char* value) {
  set_has_cd_key();
  cd_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.C2SVerifyToyCDKeyReq.cd_key)
}
inline void C2SVerifyToyCDKeyReq::set_cd_key(const char* value, size_t size) {
  set_has_cd_key();
  cd_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.C2SVerifyToyCDKeyReq.cd_key)
}
inline ::std::string* C2SVerifyToyCDKeyReq::mutable_cd_key() {
  set_has_cd_key();
  // @@protoc_insertion_point(field_mutable:message.C2SVerifyToyCDKeyReq.cd_key)
  return cd_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2SVerifyToyCDKeyReq::release_cd_key() {
  clear_has_cd_key();
  return cd_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2SVerifyToyCDKeyReq::set_allocated_cd_key(::std::string* cd_key) {
  if (cd_key != NULL) {
    set_has_cd_key();
  } else {
    clear_has_cd_key();
  }
  cd_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cd_key);
  // @@protoc_insertion_point(field_set_allocated:message.C2SVerifyToyCDKeyReq.cd_key)
}

// -------------------------------------------------------------------

// S2CVerifyToyCDKeyErrorACK

// required string cd_key = 1;
inline bool S2CVerifyToyCDKeyErrorACK::has_cd_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CVerifyToyCDKeyErrorACK::set_has_cd_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CVerifyToyCDKeyErrorACK::clear_has_cd_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CVerifyToyCDKeyErrorACK::clear_cd_key() {
  cd_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cd_key();
}
inline const ::std::string& S2CVerifyToyCDKeyErrorACK::cd_key() const {
  // @@protoc_insertion_point(field_get:message.S2CVerifyToyCDKeyErrorACK.cd_key)
  return cd_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void S2CVerifyToyCDKeyErrorACK::set_cd_key(const ::std::string& value) {
  set_has_cd_key();
  cd_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:message.S2CVerifyToyCDKeyErrorACK.cd_key)
}
inline void S2CVerifyToyCDKeyErrorACK::set_cd_key(const char* value) {
  set_has_cd_key();
  cd_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:message.S2CVerifyToyCDKeyErrorACK.cd_key)
}
inline void S2CVerifyToyCDKeyErrorACK::set_cd_key(const char* value, size_t size) {
  set_has_cd_key();
  cd_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:message.S2CVerifyToyCDKeyErrorACK.cd_key)
}
inline ::std::string* S2CVerifyToyCDKeyErrorACK::mutable_cd_key() {
  set_has_cd_key();
  // @@protoc_insertion_point(field_mutable:message.S2CVerifyToyCDKeyErrorACK.cd_key)
  return cd_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* S2CVerifyToyCDKeyErrorACK::release_cd_key() {
  clear_has_cd_key();
  return cd_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void S2CVerifyToyCDKeyErrorACK::set_allocated_cd_key(::std::string* cd_key) {
  if (cd_key != NULL) {
    set_has_cd_key();
  } else {
    clear_has_cd_key();
  }
  cd_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cd_key);
  // @@protoc_insertion_point(field_set_allocated:message.S2CVerifyToyCDKeyErrorACK.cd_key)
}

// required .message.HeroErrorCode error = 2 [default = no_error];
inline bool S2CVerifyToyCDKeyErrorACK::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CVerifyToyCDKeyErrorACK::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CVerifyToyCDKeyErrorACK::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CVerifyToyCDKeyErrorACK::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::message::HeroErrorCode S2CVerifyToyCDKeyErrorACK::error() const {
  // @@protoc_insertion_point(field_get:message.S2CVerifyToyCDKeyErrorACK.error)
  return static_cast< ::message::HeroErrorCode >(error_);
}
inline void S2CVerifyToyCDKeyErrorACK::set_error(::message::HeroErrorCode value) {
  assert(::message::HeroErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:message.S2CVerifyToyCDKeyErrorACK.error)
}

// -------------------------------------------------------------------

// S2CVerifyToyCDKeyACK

// required .message.MsgToyData ToyData = 1;
inline bool S2CVerifyToyCDKeyACK::has_toydata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CVerifyToyCDKeyACK::set_has_toydata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CVerifyToyCDKeyACK::clear_has_toydata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CVerifyToyCDKeyACK::clear_toydata() {
  if (toydata_ != NULL) toydata_->::message::MsgToyData::Clear();
  clear_has_toydata();
}
inline const ::message::MsgToyData& S2CVerifyToyCDKeyACK::toydata() const {
  // @@protoc_insertion_point(field_get:message.S2CVerifyToyCDKeyACK.ToyData)
  return toydata_ != NULL ? *toydata_ : *default_instance_->toydata_;
}
inline ::message::MsgToyData* S2CVerifyToyCDKeyACK::mutable_toydata() {
  set_has_toydata();
  if (toydata_ == NULL) {
    toydata_ = new ::message::MsgToyData;
  }
  // @@protoc_insertion_point(field_mutable:message.S2CVerifyToyCDKeyACK.ToyData)
  return toydata_;
}
inline ::message::MsgToyData* S2CVerifyToyCDKeyACK::release_toydata() {
  clear_has_toydata();
  ::message::MsgToyData* temp = toydata_;
  toydata_ = NULL;
  return temp;
}
inline void S2CVerifyToyCDKeyACK::set_allocated_toydata(::message::MsgToyData* toydata) {
  delete toydata_;
  toydata_ = toydata;
  if (toydata) {
    set_has_toydata();
  } else {
    clear_has_toydata();
  }
  // @@protoc_insertion_point(field_set_allocated:message.S2CVerifyToyCDKeyACK.ToyData)
}

// -------------------------------------------------------------------

// S2CEquipLevelUpReq

// required uint64 equip_id = 1;
inline bool S2CEquipLevelUpReq::has_equip_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CEquipLevelUpReq::set_has_equip_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CEquipLevelUpReq::clear_has_equip_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CEquipLevelUpReq::clear_equip_id() {
  equip_id_ = GOOGLE_ULONGLONG(0);
  clear_has_equip_id();
}
inline ::google::protobuf::uint64 S2CEquipLevelUpReq::equip_id() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpReq.equip_id)
  return equip_id_;
}
inline void S2CEquipLevelUpReq::set_equip_id(::google::protobuf::uint64 value) {
  set_has_equip_id();
  equip_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpReq.equip_id)
}

// -------------------------------------------------------------------

// S2CEquipLevelUpACK

// required uint64 equip_id = 1;
inline bool S2CEquipLevelUpACK::has_equip_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CEquipLevelUpACK::set_has_equip_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CEquipLevelUpACK::clear_has_equip_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CEquipLevelUpACK::clear_equip_id() {
  equip_id_ = GOOGLE_ULONGLONG(0);
  clear_has_equip_id();
}
inline ::google::protobuf::uint64 S2CEquipLevelUpACK::equip_id() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpACK.equip_id)
  return equip_id_;
}
inline void S2CEquipLevelUpACK::set_equip_id(::google::protobuf::uint64 value) {
  set_has_equip_id();
  equip_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpACK.equip_id)
}

// required int32 level = 2;
inline bool S2CEquipLevelUpACK::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CEquipLevelUpACK::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CEquipLevelUpACK::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CEquipLevelUpACK::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 S2CEquipLevelUpACK::level() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpACK.level)
  return level_;
}
inline void S2CEquipLevelUpACK::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpACK.level)
}

// required int32 gold = 3;
inline bool S2CEquipLevelUpACK::has_gold() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S2CEquipLevelUpACK::set_has_gold() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S2CEquipLevelUpACK::clear_has_gold() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S2CEquipLevelUpACK::clear_gold() {
  gold_ = 0;
  clear_has_gold();
}
inline ::google::protobuf::int32 S2CEquipLevelUpACK::gold() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpACK.gold)
  return gold_;
}
inline void S2CEquipLevelUpACK::set_gold(::google::protobuf::int32 value) {
  set_has_gold();
  gold_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpACK.gold)
}

// required int32 count = 4;
inline bool S2CEquipLevelUpACK::has_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void S2CEquipLevelUpACK::set_has_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void S2CEquipLevelUpACK::clear_has_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void S2CEquipLevelUpACK::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 S2CEquipLevelUpACK::count() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpACK.count)
  return count_;
}
inline void S2CEquipLevelUpACK::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpACK.count)
}

// required int32 diamand = 5;
inline bool S2CEquipLevelUpACK::has_diamand() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void S2CEquipLevelUpACK::set_has_diamand() {
  _has_bits_[0] |= 0x00000010u;
}
inline void S2CEquipLevelUpACK::clear_has_diamand() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void S2CEquipLevelUpACK::clear_diamand() {
  diamand_ = 0;
  clear_has_diamand();
}
inline ::google::protobuf::int32 S2CEquipLevelUpACK::diamand() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpACK.diamand)
  return diamand_;
}
inline void S2CEquipLevelUpACK::set_diamand(::google::protobuf::int32 value) {
  set_has_diamand();
  diamand_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpACK.diamand)
}

// -------------------------------------------------------------------

// S2CEquipLevelUpErrorACK

// required uint64 equip_id = 1;
inline bool S2CEquipLevelUpErrorACK::has_equip_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CEquipLevelUpErrorACK::set_has_equip_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CEquipLevelUpErrorACK::clear_has_equip_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CEquipLevelUpErrorACK::clear_equip_id() {
  equip_id_ = GOOGLE_ULONGLONG(0);
  clear_has_equip_id();
}
inline ::google::protobuf::uint64 S2CEquipLevelUpErrorACK::equip_id() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpErrorACK.equip_id)
  return equip_id_;
}
inline void S2CEquipLevelUpErrorACK::set_equip_id(::google::protobuf::uint64 value) {
  set_has_equip_id();
  equip_id_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpErrorACK.equip_id)
}

// required .message.HeroErrorCode error = 2 [default = no_error];
inline bool S2CEquipLevelUpErrorACK::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CEquipLevelUpErrorACK::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CEquipLevelUpErrorACK::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CEquipLevelUpErrorACK::clear_error() {
  error_ = 0;
  clear_has_error();
}
inline ::message::HeroErrorCode S2CEquipLevelUpErrorACK::error() const {
  // @@protoc_insertion_point(field_get:message.S2CEquipLevelUpErrorACK.error)
  return static_cast< ::message::HeroErrorCode >(error_);
}
inline void S2CEquipLevelUpErrorACK::set_error(::message::HeroErrorCode value) {
  assert(::message::HeroErrorCode_IsValid(value));
  set_has_error();
  error_ = value;
  // @@protoc_insertion_point(field_set:message.S2CEquipLevelUpErrorACK.error)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dream_5fhero_2eproto__INCLUDED
