// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gate_game.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg_gate_game.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

namespace {

const ::google::protobuf::Descriptor* MsgGT2GSAddUser_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGT2GSAddUser_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgGT2GSRemoveUser_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGT2GSRemoveUser_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgGT2GSOfflineUser_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGT2GSOfflineUser_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgGS2GTOnlines_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGS2GTOnlines_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto() {
  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg_gate_game.proto");
  GOOGLE_CHECK(file != NULL);
  MsgGT2GSAddUser_descriptor_ = file->message_type(0);
  static const int MsgGT2GSAddUser_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSAddUser, data_),
  };
  MsgGT2GSAddUser_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgGT2GSAddUser_descriptor_,
      MsgGT2GSAddUser::default_instance_,
      MsgGT2GSAddUser_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSAddUser, _has_bits_[0]),
      -1,
      -1,
      sizeof(MsgGT2GSAddUser),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSAddUser, _internal_metadata_),
      -1);
  MsgGT2GSRemoveUser_descriptor_ = file->message_type(1);
  static const int MsgGT2GSRemoveUser_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSRemoveUser, trans_),
  };
  MsgGT2GSRemoveUser_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgGT2GSRemoveUser_descriptor_,
      MsgGT2GSRemoveUser::default_instance_,
      MsgGT2GSRemoveUser_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSRemoveUser, _has_bits_[0]),
      -1,
      -1,
      sizeof(MsgGT2GSRemoveUser),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSRemoveUser, _internal_metadata_),
      -1);
  MsgGT2GSOfflineUser_descriptor_ = file->message_type(2);
  static const int MsgGT2GSOfflineUser_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSOfflineUser, trans_),
  };
  MsgGT2GSOfflineUser_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgGT2GSOfflineUser_descriptor_,
      MsgGT2GSOfflineUser::default_instance_,
      MsgGT2GSOfflineUser_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSOfflineUser, _has_bits_[0]),
      -1,
      -1,
      sizeof(MsgGT2GSOfflineUser),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSOfflineUser, _internal_metadata_),
      -1);
  MsgGS2GTOnlines_descriptor_ = file->message_type(3);
  static const int MsgGS2GTOnlines_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGS2GTOnlines, onlines_),
  };
  MsgGS2GTOnlines_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgGS2GTOnlines_descriptor_,
      MsgGS2GTOnlines::default_instance_,
      MsgGS2GTOnlines_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGS2GTOnlines, _has_bits_[0]),
      -1,
      -1,
      sizeof(MsgGS2GTOnlines),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGS2GTOnlines, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_5fgate_5fgame_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgGT2GSAddUser_descriptor_, &MsgGT2GSAddUser::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgGT2GSRemoveUser_descriptor_, &MsgGT2GSRemoveUser::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgGT2GSOfflineUser_descriptor_, &MsgGT2GSOfflineUser::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgGS2GTOnlines_descriptor_, &MsgGS2GTOnlines::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto() {
  delete MsgGT2GSAddUser::default_instance_;
  delete MsgGT2GSAddUser_reflection_;
  delete MsgGT2GSRemoveUser::default_instance_;
  delete MsgGT2GSRemoveUser_reflection_;
  delete MsgGT2GSOfflineUser::default_instance_;
  delete MsgGT2GSOfflineUser_reflection_;
  delete MsgGS2GTOnlines::default_instance_;
  delete MsgGS2GTOnlines_reflection_;
}

void protobuf_AddDesc_msg_5fgate_5fgame_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::message::protobuf_AddDesc_msg_5fgate_5flogin_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023msg_gate_game.proto\022\007message\032\024msg_gate"
    "_login.proto\"2\n\017MsgGT2GSAddUser\022\037\n\004data\030"
    "\001 \002(\0132\021.message.GTLGData\"#\n\022MsgGT2GSRemo"
    "veUser\022\r\n\005trans\030\001 \002(\r\"$\n\023MsgGT2GSOffline"
    "User\022\r\n\005trans\030\001 \002(\r\"\"\n\017MsgGS2GTOnlines\022\017"
    "\n\007onlines\030\001 \002(\r", 215);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_gate_game.proto", &protobuf_RegisterTypes);
  MsgGT2GSAddUser::default_instance_ = new MsgGT2GSAddUser();
  MsgGT2GSRemoveUser::default_instance_ = new MsgGT2GSRemoveUser();
  MsgGT2GSOfflineUser::default_instance_ = new MsgGT2GSOfflineUser();
  MsgGS2GTOnlines::default_instance_ = new MsgGS2GTOnlines();
  MsgGT2GSAddUser::default_instance_->InitAsDefaultInstance();
  MsgGT2GSRemoveUser::default_instance_->InitAsDefaultInstance();
  MsgGT2GSOfflineUser::default_instance_->InitAsDefaultInstance();
  MsgGS2GTOnlines::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_5fgate_5fgame_2eproto {
  StaticDescriptorInitializer_msg_5fgate_5fgame_2eproto() {
    protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  }
} static_descriptor_initializer_msg_5fgate_5fgame_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int MsgGT2GSAddUser::kDataFieldNumber;
#endif  // !_MSC_VER

MsgGT2GSAddUser::MsgGT2GSAddUser()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.MsgGT2GSAddUser)
}

void MsgGT2GSAddUser::InitAsDefaultInstance() {
  data_ = const_cast< ::message::GTLGData*>(&::message::GTLGData::default_instance());
}

MsgGT2GSAddUser::MsgGT2GSAddUser(const MsgGT2GSAddUser& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.MsgGT2GSAddUser)
}

void MsgGT2GSAddUser::SharedCtor() {
  _cached_size_ = 0;
  data_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGT2GSAddUser::~MsgGT2GSAddUser() {
  // @@protoc_insertion_point(destructor:message.MsgGT2GSAddUser)
  SharedDtor();
}

void MsgGT2GSAddUser::SharedDtor() {
  if (this != default_instance_) {
    delete data_;
  }
}

void MsgGT2GSAddUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGT2GSAddUser::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGT2GSAddUser_descriptor_;
}

const MsgGT2GSAddUser& MsgGT2GSAddUser::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGT2GSAddUser* MsgGT2GSAddUser::default_instance_ = NULL;

MsgGT2GSAddUser* MsgGT2GSAddUser::New(::google::protobuf::Arena* arena) const {
  MsgGT2GSAddUser* n = new MsgGT2GSAddUser;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgGT2GSAddUser::Clear() {
  if (has_data()) {
    if (data_ != NULL) data_->::message::GTLGData::Clear();
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MsgGT2GSAddUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.MsgGT2GSAddUser)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .message.GTLGData data = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.MsgGT2GSAddUser)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.MsgGT2GSAddUser)
  return false;
#undef DO_
}

void MsgGT2GSAddUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.MsgGT2GSAddUser)
  // required .message.GTLGData data = 1;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->data_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.MsgGT2GSAddUser)
}

::google::protobuf::uint8* MsgGT2GSAddUser::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.MsgGT2GSAddUser)
  // required .message.GTLGData data = 1;
  if (has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->data_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.MsgGT2GSAddUser)
  return target;
}

int MsgGT2GSAddUser::ByteSize() const {
  int total_size = 0;

  // required .message.GTLGData data = 1;
  if (has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGT2GSAddUser::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgGT2GSAddUser* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGT2GSAddUser*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGT2GSAddUser::MergeFrom(const MsgGT2GSAddUser& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_data()) {
      mutable_data()->::message::GTLGData::MergeFrom(from.data());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MsgGT2GSAddUser::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGT2GSAddUser::CopyFrom(const MsgGT2GSAddUser& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGT2GSAddUser::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_data()) {
    if (!this->data_->IsInitialized()) return false;
  }
  return true;
}

void MsgGT2GSAddUser::Swap(MsgGT2GSAddUser* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgGT2GSAddUser::InternalSwap(MsgGT2GSAddUser* other) {
  std::swap(data_, other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgGT2GSAddUser::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGT2GSAddUser_descriptor_;
  metadata.reflection = MsgGT2GSAddUser_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgGT2GSAddUser

// required .message.GTLGData data = 1;
 bool MsgGT2GSAddUser::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void MsgGT2GSAddUser::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
 void MsgGT2GSAddUser::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
 void MsgGT2GSAddUser::clear_data() {
  if (data_ != NULL) data_->::message::GTLGData::Clear();
  clear_has_data();
}
 const ::message::GTLGData& MsgGT2GSAddUser::data() const {
  // @@protoc_insertion_point(field_get:message.MsgGT2GSAddUser.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
 ::message::GTLGData* MsgGT2GSAddUser::mutable_data() {
  set_has_data();
  if (data_ == NULL) {
    data_ = new ::message::GTLGData;
  }
  // @@protoc_insertion_point(field_mutable:message.MsgGT2GSAddUser.data)
  return data_;
}
 ::message::GTLGData* MsgGT2GSAddUser::release_data() {
  clear_has_data();
  ::message::GTLGData* temp = data_;
  data_ = NULL;
  return temp;
}
 void MsgGT2GSAddUser::set_allocated_data(::message::GTLGData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
  // @@protoc_insertion_point(field_set_allocated:message.MsgGT2GSAddUser.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int MsgGT2GSRemoveUser::kTransFieldNumber;
#endif  // !_MSC_VER

MsgGT2GSRemoveUser::MsgGT2GSRemoveUser()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.MsgGT2GSRemoveUser)
}

void MsgGT2GSRemoveUser::InitAsDefaultInstance() {
}

MsgGT2GSRemoveUser::MsgGT2GSRemoveUser(const MsgGT2GSRemoveUser& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.MsgGT2GSRemoveUser)
}

void MsgGT2GSRemoveUser::SharedCtor() {
  _cached_size_ = 0;
  trans_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGT2GSRemoveUser::~MsgGT2GSRemoveUser() {
  // @@protoc_insertion_point(destructor:message.MsgGT2GSRemoveUser)
  SharedDtor();
}

void MsgGT2GSRemoveUser::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgGT2GSRemoveUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGT2GSRemoveUser::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGT2GSRemoveUser_descriptor_;
}

const MsgGT2GSRemoveUser& MsgGT2GSRemoveUser::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGT2GSRemoveUser* MsgGT2GSRemoveUser::default_instance_ = NULL;

MsgGT2GSRemoveUser* MsgGT2GSRemoveUser::New(::google::protobuf::Arena* arena) const {
  MsgGT2GSRemoveUser* n = new MsgGT2GSRemoveUser;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgGT2GSRemoveUser::Clear() {
  trans_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MsgGT2GSRemoveUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.MsgGT2GSRemoveUser)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 trans = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &trans_)));
          set_has_trans();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.MsgGT2GSRemoveUser)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.MsgGT2GSRemoveUser)
  return false;
#undef DO_
}

void MsgGT2GSRemoveUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.MsgGT2GSRemoveUser)
  // required uint32 trans = 1;
  if (has_trans()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->trans(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.MsgGT2GSRemoveUser)
}

::google::protobuf::uint8* MsgGT2GSRemoveUser::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.MsgGT2GSRemoveUser)
  // required uint32 trans = 1;
  if (has_trans()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->trans(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.MsgGT2GSRemoveUser)
  return target;
}

int MsgGT2GSRemoveUser::ByteSize() const {
  int total_size = 0;

  // required uint32 trans = 1;
  if (has_trans()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->trans());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGT2GSRemoveUser::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgGT2GSRemoveUser* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGT2GSRemoveUser*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGT2GSRemoveUser::MergeFrom(const MsgGT2GSRemoveUser& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_trans()) {
      set_trans(from.trans());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MsgGT2GSRemoveUser::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGT2GSRemoveUser::CopyFrom(const MsgGT2GSRemoveUser& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGT2GSRemoveUser::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgGT2GSRemoveUser::Swap(MsgGT2GSRemoveUser* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgGT2GSRemoveUser::InternalSwap(MsgGT2GSRemoveUser* other) {
  std::swap(trans_, other->trans_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgGT2GSRemoveUser::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGT2GSRemoveUser_descriptor_;
  metadata.reflection = MsgGT2GSRemoveUser_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgGT2GSRemoveUser

// required uint32 trans = 1;
 bool MsgGT2GSRemoveUser::has_trans() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void MsgGT2GSRemoveUser::set_has_trans() {
  _has_bits_[0] |= 0x00000001u;
}
 void MsgGT2GSRemoveUser::clear_has_trans() {
  _has_bits_[0] &= ~0x00000001u;
}
 void MsgGT2GSRemoveUser::clear_trans() {
  trans_ = 0u;
  clear_has_trans();
}
 ::google::protobuf::uint32 MsgGT2GSRemoveUser::trans() const {
  // @@protoc_insertion_point(field_get:message.MsgGT2GSRemoveUser.trans)
  return trans_;
}
 void MsgGT2GSRemoveUser::set_trans(::google::protobuf::uint32 value) {
  set_has_trans();
  trans_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGT2GSRemoveUser.trans)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int MsgGT2GSOfflineUser::kTransFieldNumber;
#endif  // !_MSC_VER

MsgGT2GSOfflineUser::MsgGT2GSOfflineUser()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.MsgGT2GSOfflineUser)
}

void MsgGT2GSOfflineUser::InitAsDefaultInstance() {
}

MsgGT2GSOfflineUser::MsgGT2GSOfflineUser(const MsgGT2GSOfflineUser& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.MsgGT2GSOfflineUser)
}

void MsgGT2GSOfflineUser::SharedCtor() {
  _cached_size_ = 0;
  trans_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGT2GSOfflineUser::~MsgGT2GSOfflineUser() {
  // @@protoc_insertion_point(destructor:message.MsgGT2GSOfflineUser)
  SharedDtor();
}

void MsgGT2GSOfflineUser::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgGT2GSOfflineUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGT2GSOfflineUser::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGT2GSOfflineUser_descriptor_;
}

const MsgGT2GSOfflineUser& MsgGT2GSOfflineUser::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGT2GSOfflineUser* MsgGT2GSOfflineUser::default_instance_ = NULL;

MsgGT2GSOfflineUser* MsgGT2GSOfflineUser::New(::google::protobuf::Arena* arena) const {
  MsgGT2GSOfflineUser* n = new MsgGT2GSOfflineUser;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgGT2GSOfflineUser::Clear() {
  trans_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MsgGT2GSOfflineUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.MsgGT2GSOfflineUser)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 trans = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &trans_)));
          set_has_trans();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.MsgGT2GSOfflineUser)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.MsgGT2GSOfflineUser)
  return false;
#undef DO_
}

void MsgGT2GSOfflineUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.MsgGT2GSOfflineUser)
  // required uint32 trans = 1;
  if (has_trans()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->trans(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.MsgGT2GSOfflineUser)
}

::google::protobuf::uint8* MsgGT2GSOfflineUser::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.MsgGT2GSOfflineUser)
  // required uint32 trans = 1;
  if (has_trans()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->trans(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.MsgGT2GSOfflineUser)
  return target;
}

int MsgGT2GSOfflineUser::ByteSize() const {
  int total_size = 0;

  // required uint32 trans = 1;
  if (has_trans()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->trans());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGT2GSOfflineUser::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgGT2GSOfflineUser* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGT2GSOfflineUser*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGT2GSOfflineUser::MergeFrom(const MsgGT2GSOfflineUser& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_trans()) {
      set_trans(from.trans());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MsgGT2GSOfflineUser::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGT2GSOfflineUser::CopyFrom(const MsgGT2GSOfflineUser& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGT2GSOfflineUser::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgGT2GSOfflineUser::Swap(MsgGT2GSOfflineUser* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgGT2GSOfflineUser::InternalSwap(MsgGT2GSOfflineUser* other) {
  std::swap(trans_, other->trans_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgGT2GSOfflineUser::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGT2GSOfflineUser_descriptor_;
  metadata.reflection = MsgGT2GSOfflineUser_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgGT2GSOfflineUser

// required uint32 trans = 1;
 bool MsgGT2GSOfflineUser::has_trans() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void MsgGT2GSOfflineUser::set_has_trans() {
  _has_bits_[0] |= 0x00000001u;
}
 void MsgGT2GSOfflineUser::clear_has_trans() {
  _has_bits_[0] &= ~0x00000001u;
}
 void MsgGT2GSOfflineUser::clear_trans() {
  trans_ = 0u;
  clear_has_trans();
}
 ::google::protobuf::uint32 MsgGT2GSOfflineUser::trans() const {
  // @@protoc_insertion_point(field_get:message.MsgGT2GSOfflineUser.trans)
  return trans_;
}
 void MsgGT2GSOfflineUser::set_trans(::google::protobuf::uint32 value) {
  set_has_trans();
  trans_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGT2GSOfflineUser.trans)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int MsgGS2GTOnlines::kOnlinesFieldNumber;
#endif  // !_MSC_VER

MsgGS2GTOnlines::MsgGS2GTOnlines()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.MsgGS2GTOnlines)
}

void MsgGS2GTOnlines::InitAsDefaultInstance() {
}

MsgGS2GTOnlines::MsgGS2GTOnlines(const MsgGS2GTOnlines& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.MsgGS2GTOnlines)
}

void MsgGS2GTOnlines::SharedCtor() {
  _cached_size_ = 0;
  onlines_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGS2GTOnlines::~MsgGS2GTOnlines() {
  // @@protoc_insertion_point(destructor:message.MsgGS2GTOnlines)
  SharedDtor();
}

void MsgGS2GTOnlines::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgGS2GTOnlines::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGS2GTOnlines::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGS2GTOnlines_descriptor_;
}

const MsgGS2GTOnlines& MsgGS2GTOnlines::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGS2GTOnlines* MsgGS2GTOnlines::default_instance_ = NULL;

MsgGS2GTOnlines* MsgGS2GTOnlines::New(::google::protobuf::Arena* arena) const {
  MsgGS2GTOnlines* n = new MsgGS2GTOnlines;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgGS2GTOnlines::Clear() {
  onlines_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MsgGS2GTOnlines::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.MsgGS2GTOnlines)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 onlines = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &onlines_)));
          set_has_onlines();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.MsgGS2GTOnlines)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.MsgGS2GTOnlines)
  return false;
#undef DO_
}

void MsgGS2GTOnlines::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.MsgGS2GTOnlines)
  // required uint32 onlines = 1;
  if (has_onlines()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->onlines(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.MsgGS2GTOnlines)
}

::google::protobuf::uint8* MsgGS2GTOnlines::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.MsgGS2GTOnlines)
  // required uint32 onlines = 1;
  if (has_onlines()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->onlines(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.MsgGS2GTOnlines)
  return target;
}

int MsgGS2GTOnlines::ByteSize() const {
  int total_size = 0;

  // required uint32 onlines = 1;
  if (has_onlines()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->onlines());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGS2GTOnlines::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgGS2GTOnlines* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGS2GTOnlines*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGS2GTOnlines::MergeFrom(const MsgGS2GTOnlines& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_onlines()) {
      set_onlines(from.onlines());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MsgGS2GTOnlines::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGS2GTOnlines::CopyFrom(const MsgGS2GTOnlines& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGS2GTOnlines::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgGS2GTOnlines::Swap(MsgGS2GTOnlines* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgGS2GTOnlines::InternalSwap(MsgGS2GTOnlines* other) {
  std::swap(onlines_, other->onlines_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgGS2GTOnlines::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGS2GTOnlines_descriptor_;
  metadata.reflection = MsgGS2GTOnlines_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgGS2GTOnlines

// required uint32 onlines = 1;
 bool MsgGS2GTOnlines::has_onlines() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
 void MsgGS2GTOnlines::set_has_onlines() {
  _has_bits_[0] |= 0x00000001u;
}
 void MsgGS2GTOnlines::clear_has_onlines() {
  _has_bits_[0] &= ~0x00000001u;
}
 void MsgGS2GTOnlines::clear_onlines() {
  onlines_ = 0u;
  clear_has_onlines();
}
 ::google::protobuf::uint32 MsgGS2GTOnlines::onlines() const {
  // @@protoc_insertion_point(field_get:message.MsgGS2GTOnlines.onlines)
  return onlines_;
}
 void MsgGS2GTOnlines::set_onlines(::google::protobuf::uint32 value) {
  set_has_onlines();
  onlines_ = value;
  // @@protoc_insertion_point(field_set:message.MsgGS2GTOnlines.onlines)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
