// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgs2c.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msgs2c.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

namespace {

const ::google::protobuf::Descriptor* MsgS2CCreatePlayerError_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgS2CCreatePlayerError_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* enumCreateCharResult_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_msgs2c_2eproto() {
  protobuf_AddDesc_msgs2c_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msgs2c.proto");
  GOOGLE_CHECK(file != NULL);
  MsgS2CCreatePlayerError_descriptor_ = file->message_type(0);
  static const int MsgS2CCreatePlayerError_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgS2CCreatePlayerError, result_),
  };
  MsgS2CCreatePlayerError_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgS2CCreatePlayerError_descriptor_,
      MsgS2CCreatePlayerError::default_instance_,
      MsgS2CCreatePlayerError_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgS2CCreatePlayerError, _has_bits_[0]),
      -1,
      -1,
      sizeof(MsgS2CCreatePlayerError),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgS2CCreatePlayerError, _internal_metadata_),
      -1);
  enumCreateCharResult_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msgs2c_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgS2CCreatePlayerError_descriptor_, &MsgS2CCreatePlayerError::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msgs2c_2eproto() {
  delete MsgS2CCreatePlayerError::default_instance_;
  delete MsgS2CCreatePlayerError_reflection_;
}

void protobuf_AddDesc_msgs2c_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014msgs2c.proto\022\007message\"H\n\027MsgS2CCreateP"
    "layerError\022-\n\006result\030\001 \002(\0162\035.message.enu"
    "mCreateCharResult*Z\n\024enumCreateCharResul"
    "t\022\022\n\016Create_Success\020\000\022\026\n\022Create_SystemEr"
    "ror\020\001\022\026\n\022Create_Name_Repeat\020\002", 189);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msgs2c.proto", &protobuf_RegisterTypes);
  MsgS2CCreatePlayerError::default_instance_ = new MsgS2CCreatePlayerError();
  MsgS2CCreatePlayerError::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msgs2c_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msgs2c_2eproto {
  StaticDescriptorInitializer_msgs2c_2eproto() {
    protobuf_AddDesc_msgs2c_2eproto();
  }
} static_descriptor_initializer_msgs2c_2eproto_;
const ::google::protobuf::EnumDescriptor* enumCreateCharResult_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return enumCreateCharResult_descriptor_;
}
bool enumCreateCharResult_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int MsgS2CCreatePlayerError::kResultFieldNumber;
#endif  // !_MSC_VER

MsgS2CCreatePlayerError::MsgS2CCreatePlayerError()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.MsgS2CCreatePlayerError)
}

void MsgS2CCreatePlayerError::InitAsDefaultInstance() {
}

MsgS2CCreatePlayerError::MsgS2CCreatePlayerError(const MsgS2CCreatePlayerError& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:message.MsgS2CCreatePlayerError)
}

void MsgS2CCreatePlayerError::SharedCtor() {
  _cached_size_ = 0;
  result_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgS2CCreatePlayerError::~MsgS2CCreatePlayerError() {
  // @@protoc_insertion_point(destructor:message.MsgS2CCreatePlayerError)
  SharedDtor();
}

void MsgS2CCreatePlayerError::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgS2CCreatePlayerError::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgS2CCreatePlayerError::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgS2CCreatePlayerError_descriptor_;
}

const MsgS2CCreatePlayerError& MsgS2CCreatePlayerError::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msgs2c_2eproto();
  return *default_instance_;
}

MsgS2CCreatePlayerError* MsgS2CCreatePlayerError::default_instance_ = NULL;

MsgS2CCreatePlayerError* MsgS2CCreatePlayerError::New(::google::protobuf::Arena* arena) const {
  MsgS2CCreatePlayerError* n = new MsgS2CCreatePlayerError;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgS2CCreatePlayerError::Clear() {
  result_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool MsgS2CCreatePlayerError::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:message.MsgS2CCreatePlayerError)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .message.enumCreateCharResult result = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::message::enumCreateCharResult_IsValid(value)) {
            set_result(static_cast< ::message::enumCreateCharResult >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:message.MsgS2CCreatePlayerError)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:message.MsgS2CCreatePlayerError)
  return false;
#undef DO_
}

void MsgS2CCreatePlayerError::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:message.MsgS2CCreatePlayerError)
  // required .message.enumCreateCharResult result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->result(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:message.MsgS2CCreatePlayerError)
}

::google::protobuf::uint8* MsgS2CCreatePlayerError::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.MsgS2CCreatePlayerError)
  // required .message.enumCreateCharResult result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->result(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.MsgS2CCreatePlayerError)
  return target;
}

int MsgS2CCreatePlayerError::ByteSize() const {
  int total_size = 0;

  // required .message.enumCreateCharResult result = 1;
  if (has_result()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->result());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgS2CCreatePlayerError::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MsgS2CCreatePlayerError* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgS2CCreatePlayerError*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgS2CCreatePlayerError::MergeFrom(const MsgS2CCreatePlayerError& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void MsgS2CCreatePlayerError::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgS2CCreatePlayerError::CopyFrom(const MsgS2CCreatePlayerError& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgS2CCreatePlayerError::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgS2CCreatePlayerError::Swap(MsgS2CCreatePlayerError* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgS2CCreatePlayerError::InternalSwap(MsgS2CCreatePlayerError* other) {
  std::swap(result_, other->result_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgS2CCreatePlayerError::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgS2CCreatePlayerError_descriptor_;
  metadata.reflection = MsgS2CCreatePlayerError_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
